/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AccessDataBaseCRUD;

import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class StudentCRUD extends javax.swing.JFrame {

    /**
     * Creates new form StudentCRUD
     */
    public StudentCRUD() {
        initComponents();
        JLoadComboBoxDegree();
        LoadJTableStudent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelRollNumber = new javax.swing.JLabel();
        jTextFieldRollNumber = new javax.swing.JTextField();
        jLabelPhoneNumber = new javax.swing.JLabel();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jLabelGender = new javax.swing.JLabel();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jLabelGender1 = new javax.swing.JLabel();
        jComboBoxDegree = new javax.swing.JComboBox<>();
        jButtonAddStudent = new javax.swing.JButton();
        jButtonDeleteStudent = new javax.swing.JButton();
        jButtonUpdateStudent = new javax.swing.JButton();
        jButtonSerachStudent = new javax.swing.JButton();
        jButtonAddNewDegree = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableStudent = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelName.setText("Name");

        jTextFieldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNameActionPerformed(evt);
            }
        });

        jLabelRollNumber.setText("Roll Number");

        jLabelPhoneNumber.setText("Phone Number");

        jLabelGender.setText("Gender");

        buttonGroup1.add(jRadioButtonMale);
        jRadioButtonMale.setText("Male");

        buttonGroup1.add(jRadioButtonFemale);
        jRadioButtonFemale.setText("Female");
        jRadioButtonFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFemaleActionPerformed(evt);
            }
        });

        jLabelGender1.setText("Degree");

        jComboBoxDegree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", " ", " " }));

        jButtonAddStudent.setText("Add Student");
        jButtonAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddStudentActionPerformed(evt);
            }
        });

        jButtonDeleteStudent.setText("Delete Student");
        jButtonDeleteStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteStudentActionPerformed(evt);
            }
        });

        jButtonUpdateStudent.setText("Update Student");
        jButtonUpdateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateStudentActionPerformed(evt);
            }
        });

        jButtonSerachStudent.setText("Search Student");
        jButtonSerachStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSerachStudentActionPerformed(evt);
            }
        });

        jButtonAddNewDegree.setText(" Add New Degree");
        jButtonAddNewDegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNewDegreeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelName)
                            .addComponent(jLabelRollNumber))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldRollNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPhoneNumber)
                            .addComponent(jLabelGender)
                            .addComponent(jLabelGender1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonMale)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonFemale))
                            .addComponent(jComboBoxDegree, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAddStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDeleteStudent)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonUpdateStudent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSerachStudent))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonAddNewDegree)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelName)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelRollNumber)
                    .addComponent(jTextFieldRollNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhoneNumber)
                    .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonMale)
                        .addComponent(jRadioButtonFemale))
                    .addComponent(jLabelGender, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelGender1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonAddNewDegree)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeleteStudent)
                    .addComponent(jButtonAddStudent)
                    .addComponent(jButtonUpdateStudent)
                    .addComponent(jButtonSerachStudent)))
        );

        jTableStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Roll Number", "Phone Number", "Gender", "Degree"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Short.class, java.lang.Integer.class, java.lang.Short.class, java.lang.Short.class, java.lang.Short.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableStudent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNameActionPerformed

    }//GEN-LAST:event_jTextFieldNameActionPerformed

    
    
    private void jRadioButtonFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFemaleActionPerformed
   // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonFemaleActionPerformed

    private void jButtonAddStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddStudentActionPerformed
        int rollNumber = Integer.parseInt(jTextFieldRollNumber.getText());
        String name = jTextFieldName.getText();
        String phoneNumber = jTextFieldPhoneNumber.getText();
        String gender = null;
        if(jRadioButtonMale.isSelected()){
            gender = jRadioButtonMale.getText();
        }else{
            gender = jRadioButtonFemale.getText();
        } 
        String degree = jComboBoxDegree.getSelectedItem().toString();
        Student stu = new Student(name,rollNumber,phoneNumber,gender,degree);
        if(stu.addStudent()){
            JOptionPane.showMessageDialog(null,"Student Record inserted successfully");
        }else{
            JOptionPane.showMessageDialog(null,"Student Record not inserted successfully");           
        }
        LoadJTableStudent();
    }//GEN-LAST:event_jButtonAddStudentActionPerformed

    private void jButtonDeleteStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteStudentActionPerformed
        Student stu = new Student();
        stu.setRollNumber(Integer.parseInt(jTextFieldRollNumber.getText()));
        if(stu.deleteStudent()){
            JOptionPane.showMessageDialog(null,"Student Record deleted successfully");
        }else{
            JOptionPane.showMessageDialog(null,"Student Record not deleted successfully");           
        }
        LoadJTableStudent();        
    }//GEN-LAST:event_jButtonDeleteStudentActionPerformed

    private void jButtonUpdateStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateStudentActionPerformed
        int rollNumber = Integer.parseInt(jTextFieldRollNumber.getText());
        String name = jTextFieldName.getText();
        String phoneNumber = jTextFieldPhoneNumber.getText();
        String gender = null;
        if(jRadioButtonMale.isSelected()){
            gender = jRadioButtonMale.getText();
        }else{
            gender = jRadioButtonFemale.getText();
        } 
        String degree = jComboBoxDegree.getSelectedItem().toString();
        Student stu = new Student(name,rollNumber,phoneNumber,gender,degree);
        if(stu.updateStudent()){
            JOptionPane.showMessageDialog(null,"Student Record updated successfully");
        }else{
            JOptionPane.showMessageDialog(null,"Student Record not updated successfully");           
        }
        LoadJTableStudent();
        
    }//GEN-LAST:event_jButtonUpdateStudentActionPerformed

    private void jButtonSerachStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSerachStudentActionPerformed
        int rollNumber = Integer.parseInt(jTextFieldRollNumber.getText());
       String query ="Select * from students where student_roll_number = '"+rollNumber+"'";
        Connect con = new Connect();
        con.openConnection();
        ResultSet rs = con.Search(query);
        try {
            if(rs.next()){
                jTextFieldRollNumber.setText(rs.getInt("student_roll_number")+"");
                jTextFieldName.setText(rs.getString("student_name"));
                jTextFieldPhoneNumber.setText(rs.getString("student_phone_number"));
                String gender = null;
                if(rs.getString("student_gender").equals("male")){
                    jRadioButtonMale.setSelected(true);
                }else{
                    jRadioButtonFemale.setSelected(true);
                }
                jComboBoxDegree.setSelectedItem(rs.getString("student_degree"));
            }} catch (SQLException ex) {
            Logger.getLogger(StudentCRUD.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            con.closeConnection();
        }
    }//GEN-LAST:event_jButtonSerachStudentActionPerformed

    private void jButtonAddNewDegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNewDegreeActionPerformed
        new AddNewDegreeForm();
    }//GEN-LAST:event_jButtonAddNewDegreeActionPerformed
    
    public void LoadJTableStudent(){
        String query = "Select * from students";
        Connect con = new Connect(); 
        con.openConnection();
        ResultSet rs = con.Search(query);
        DefaultTableModel model = (DefaultTableModel) this.jTableStudent.getModel();
        for(int i=this.jTableStudent.getRowCount()-1;i>=0;i--){
            model.removeRow(i);
        }
        try {
            while(rs.next()){
                model.addRow(
                    new Object[]{
                        rs.getInt("student_iD"),
                        rs.getString("student_name"),
                        rs.getInt("student_roll_number"),
                        rs.getString("student_phone_number"),
                        rs.getString("student_gender"),
                        rs.getString("student_degree"),
                    }
            );
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(StudentCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            con.closeConnection();
        }
       
}
    public void JLoadComboBoxDegree(){
        String query = "Select * FROM Degrees";
        Connect con = new Connect();
        con.openConnection();
        ResultSet rs = con.Search(query);
        
        try {
            while(rs.next()){
                jComboBoxDegree.addItem(rs.getString("degree_title"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            con.closeConnection();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentCRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentCRUD().setVisible(true);
            }
        });
        Connect con = new Connect();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAddNewDegree;
    private javax.swing.JButton jButtonAddStudent;
    private javax.swing.JButton jButtonDeleteStudent;
    private javax.swing.JButton jButtonSerachStudent;
    private javax.swing.JButton jButtonUpdateStudent;
    private javax.swing.JComboBox<String> jComboBoxDegree;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelGender1;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPhoneNumber;
    private javax.swing.JLabel jLabelRollNumber;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableStudent;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JTextField jTextFieldRollNumber;
    // End of variables declaration//GEN-END:variables
}
